version: "3.7"

services:
    # imagem micro-email
    micro_email:
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - redis
            - queue
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices-email

    # queue
    queue:
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - microservices-email

    #nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8002:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices-email
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # redis
    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            - microservices-email

networks:
    microservices-email:
        driver: bridge
